# Multiple Linear Regression

In [58]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [59]:
data = pd.read_csv('Startups.csv')

In [60]:
data.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [61]:
X = data.iloc[:, :-1]
X.head()

   R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

In [62]:
y = data.iloc[:, 4]
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [63]:
#Convert the column into categorical columns

states=pd.get_dummies(X['State'],drop_first=True)
states

    Florida  New York
0         0         1
1         0         0
2         1         0
3         0         1
4         1         0
5         0         1
6         0         0
7         1         0
8         0         1
9         0         0
10        1         0
11        0         0
12        1         0
13        0         0
14        1         0
15        0         1
16        0         0
17        0         1
18        1         0
19        0         1
20        0         0
21        0         1
22        1         0
23        1         0
24        0         1
25        0         0
26        1         0
27        0         1
28        1         0
29        0         1
30        1         0
31        0         1
32        0         0
33        1         0
34        0         0
35        0         1
36        1         0
37        0         0
38        0         1
39        0         0
40        0         0
41        1         0
42        0         0
43        0         1
44        0         0
45        0         1
46        1         0
47        0         0
48        0         1
49        0         0

In [68]:
# Drop the state coulmn
X=X.drop('State',axis=1)

In [69]:
# concat the dummy variables
X=pd.concat([X,states],axis=1)

In [70]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [71]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression

In [72]:
model = LinearRegression()

In [73]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [74]:
# Predicting the Test set results
y_pred = model.predict(X_test)
y_pred

array([ 59117.70579238,  89053.4782613 ,  97658.97077936,  96530.63510972,
       126730.00313622,  45340.6731579 , 134811.00869514,  63409.25456087,
        97445.28717696, 101211.79105111])

In [75]:
model.score(X_test,y_pred)

1.0

# irisData_MultiLinear Regression

In [76]:
data = pd.read_csv('iris.csv')

In [77]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal_length      150 non-null float64
sepal_length.1    150 non-null float64
petal_length      150 non-null float64
petal_width       150 non-null float64
species           150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB

In [78]:
data.head()

   sepal_length  sepal_length.1  petal_length  petal_width species
0           5.1             3.5           1.4          0.2  setosa
1           4.9             3.0           1.4          0.2  setosa
2           4.7             3.2           1.3          0.2  setosa
3           4.6             3.1           1.5          0.2  setosa
4           5.0             3.6           1.4          0.2  setosa

In [79]:
x = data.iloc[:,:-1]

In [80]:
x.head()

   sepal_length  sepal_length.1  petal_length  petal_width
0           5.1             3.5           1.4          0.2
1           4.9             3.0           1.4          0.2
2           4.7             3.2           1.3          0.2
3           4.6             3.1           1.5          0.2
4           5.0             3.6           1.4          0.2

In [81]:
y=data.iloc[:,-1]

In [82]:
y.head()

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: species, dtype: object

In [83]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [84]:
ndf=data

In [85]:
ndf.species=lb.fit_transform(ndf.species)

In [86]:
ndf

     sepal_length  sepal_length.1  petal_length  petal_width  species
0             5.1             3.5           1.4          0.2        0
1             4.9             3.0           1.4          0.2        0
2             4.7             3.2           1.3          0.2        0
3             4.6             3.1           1.5          0.2        0
4             5.0             3.6           1.4          0.2        0
5             5.4             3.9           1.7          0.4        0
6             4.6             3.4           1.4          0.3        0
7             5.0             3.4           1.5          0.2        0
8             4.4             2.9           1.4          0.2        0
9             4.9             3.1           1.5          0.1        0
10            5.4             3.7           1.5          0.2        0
11            4.8             3.4           1.6          0.2        0
12            4.8             3.0           1.4          0.1        0
13            4.3             3.0           1.1          0.1        0
14            5.8             4.0           1.2          0.2        0
15            5.7             4.4           1.5          0.4        0
16            5.4             3.9           1.3          0.4        0
17            5.1             3.5           1.4          0.3        0
18            5.7             3.8           1.7          0.3        0
19            5.1             3.8           1.5          0.3        0
20            5.4             3.4           1.7          0.2        0
21            5.1             3.7           1.5          0.4        0
22            4.6             3.6           1.0          0.2        0
23            5.1             3.3           1.7          0.5        0
24            4.8             3.4           1.9          0.2        0
25            5.0             3.0           1.6          0.2        0
26            5.0             3.4           1.6          0.4        0
27            5.2             3.5           1.5          0.2        0
28            5.2             3.4           1.4          0.2        0
29            4.7             3.2           1.6          0.2        0
..            ...             ...           ...          ...      ...
120           6.9             3.2           5.7          2.3        2
121           5.6             2.8           4.9          2.0        2
122           7.7             2.8           6.7          2.0        2
123           6.3             2.7           4.9          1.8        2
124           6.7             3.3           5.7          2.1        2
125           7.2             3.2           6.0          1.8        2
126           6.2             2.8           4.8          1.8        2
127           6.1             3.0           4.9          1.8        2
128           6.4             2.8           5.6          2.1        2
129           7.2             3.0           5.8          1.6        2
130           7.4             2.8           6.1          1.9        2
131           7.9             3.8           6.4          2.0        2
132           6.4             2.8           5.6          2.2        2
133           6.3             2.8           5.1          1.5        2
134           6.1             2.6           5.6          1.4        2
135           7.7             3.0           6.1          2.3        2
136           6.3             3.4           5.6          2.4        2
137           6.4             3.1           5.5          1.8        2
138           6.0             3.0           4.8          1.8        2
139           6.9             3.1           5.4          2.1        2
140           6.7             3.1           5.6          2.4        2
141           6.9             3.1           5.1          2.3        2
142           5.8             2.7           5.1          1.9        2
143           6.8             3.2           5.9          2.3        2
144           6.7             3.3           5.7          2.5        2
145           6.7             3.0           5.2          2.3        2
146           6.3             2.5           5.0          1.9        2
147           6.5             3.0           5.2          2.0        2
148           6.2             3.4           5.4          2.3        2
149           5.9             3.0           5.1          1.8        2

[150 rows x 5 columns]

In [119]:
x = ndf.iloc[:,:-1]
x

     sepal_length  sepal_length.1  petal_length  petal_width
0             5.1             3.5           1.4          0.2
1             4.9             3.0           1.4          0.2
2             4.7             3.2           1.3          0.2
3             4.6             3.1           1.5          0.2
4             5.0             3.6           1.4          0.2
5             5.4             3.9           1.7          0.4
6             4.6             3.4           1.4          0.3
7             5.0             3.4           1.5          0.2
8             4.4             2.9           1.4          0.2
9             4.9             3.1           1.5          0.1
10            5.4             3.7           1.5          0.2
11            4.8             3.4           1.6          0.2
12            4.8             3.0           1.4          0.1
13            4.3             3.0           1.1          0.1
14            5.8             4.0           1.2          0.2
15            5.7             4.4           1.5          0.4
16            5.4             3.9           1.3          0.4
17            5.1             3.5           1.4          0.3
18            5.7             3.8           1.7          0.3
19            5.1             3.8           1.5          0.3
20            5.4             3.4           1.7          0.2
21            5.1             3.7           1.5          0.4
22            4.6             3.6           1.0          0.2
23            5.1             3.3           1.7          0.5
24            4.8             3.4           1.9          0.2
25            5.0             3.0           1.6          0.2
26            5.0             3.4           1.6          0.4
27            5.2             3.5           1.5          0.2
28            5.2             3.4           1.4          0.2
29            4.7             3.2           1.6          0.2
..            ...             ...           ...          ...
120           6.9             3.2           5.7          2.3
121           5.6             2.8           4.9          2.0
122           7.7             2.8           6.7          2.0
123           6.3             2.7           4.9          1.8
124           6.7             3.3           5.7          2.1
125           7.2             3.2           6.0          1.8
126           6.2             2.8           4.8          1.8
127           6.1             3.0           4.9          1.8
128           6.4             2.8           5.6          2.1
129           7.2             3.0           5.8          1.6
130           7.4             2.8           6.1          1.9
131           7.9             3.8           6.4          2.0
132           6.4             2.8           5.6          2.2
133           6.3             2.8           5.1          1.5
134           6.1             2.6           5.6          1.4
135           7.7             3.0           6.1          2.3
136           6.3             3.4           5.6          2.4
137           6.4             3.1           5.5          1.8
138           6.0             3.0           4.8          1.8
139           6.9             3.1           5.4          2.1
140           6.7             3.1           5.6          2.4
141           6.9             3.1           5.1          2.3
142           5.8             2.7           5.1          1.9
143           6.8             3.2           5.9          2.3
144           6.7             3.3           5.7          2.5
145           6.7             3.0           5.2          2.3
146           6.3             2.5           5.0          1.9
147           6.5             3.0           5.2          2.0
148           6.2             3.4           5.4          2.3
149           5.9             3.0           5.1          1.8

[150 rows x 4 columns]

In [121]:
y=ndf.iloc[:,-1]
y

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
120    2
121    2
122    2
123    2
124    2
125    2
126    2
127    2
128    2
129    2
130    2
131    2
132    2
133    2
134    2
135    2
136    2
137    2
138    2
139    2
140    2
141    2
142    2
143    2
144    2
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int32

In [122]:
from sklearn .model_selection import train_test_split

In [123]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33)

In [124]:
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [125]:
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [126]:
# Predicting the Test set results
y_pred = model.predict(x_test)
y_pred

array([ 1.71146484,  1.27269708, -0.08073612,  1.44781121, -0.04964791,
        0.06411834,  1.15759341,  2.03360147,  1.30479626, -0.09048569,
        1.82858988,  0.94669742, -0.09938594,  1.8620281 ,  1.3241215 ,
        1.23943061,  0.00277681,  1.67432469,  1.73247056,  1.77414326,
       -0.00444081, -0.01049274,  1.72222536, -0.01116441,  1.89748992,
        1.2701774 ,  1.92085263,  1.03475141,  0.07352272,  0.04764937,
        1.38461531,  1.98201166, -0.01437018,  1.52510521, -0.04225263,
        1.58610101,  0.92956269,  1.05289656,  1.16531946, -0.11955675,
        1.87110179, -0.07317546,  1.66508775,  1.32413   ,  2.23306741,
        1.98856137,  0.23652868, -0.0632605 ,  1.70995396,  1.1328879 ])

In [ ]:
y_pred = model.predict(x_test)

In [127]:
model.score(x_test,y_pred)

1.0